sudo: false
language: c++
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - re2c
            - libboost-program-options-dev
            - libboost-test-dev
            - cmake3
            - g++-5
      env:
        - CLINGO_URL="https://github.com/potassco/clingo/releases/download/v5.2.1/clingo-5.2.1-linux-x86_64.tar.gz"
        - CLINGO_NAME="clingo-5.2.1-linux-x86_64"
        - MY_CC=gcc-5
        - MY_CXX=g++-5
    - os: osx
      osx_image: xcode8.3
      env:
        - CLINGO_URL="https://github.com/potassco/clingo/releases/download/v5.2.1/clingo-5.2.1-macos-10.9.tar.gz"
        - CLINGO_NAME="clingo-5.2.1-macos-10.9"
        - MY_CC=clang
        - MY_CXX=clang++

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install re2c; fi
  - curl -LO "${CLINGO_URL}";
  - tar xf "${CLINGO_NAME}.tar.gz"
  - mkdir -p install/bin
  - cp "${CLINGO_NAME}/clasp" install/bin/
  - cp "${CLINGO_NAME}/gringo" install/bin/

script:
  - mkdir build &&
    cd build &&
    cmake
      -DCMAKE_VERBOSE_MAKEFILE=True
      -DCMAKE_C_COMPILER=${MY_CC}
      -DCMAKE_CXX_COMPILER=${MY_CXX}
      -DCMAKE_INSTALL_PREFIX="${TRAVIS_BUILD_DIR}/install/"
      -DASPCUD_ENCODING_PATH="<module_path>/../share/aspcud/specification.lp"
      .. &&
    make -j3 &&
    make test CTEST_OUTPUT_ON_FAILURE=True &&
    make install
  - install/bin/aspcud --help
  - install/bin/aspcud -c paranoid examples/feature.cudf
  - install/bin/aspcud -c paranoid examples/feature.cudf solution.cudf
  - cat solution.cudf
  - install/bin/aspcud examples/feature.cudf solution.cudf paranoid
  - cat solution.cudf

